# This file was generated by GoReleaser. DO NOT EDIT.
cask "awf" do
  desc "Find AWS resources"
  homepage "https://github.com/pete911/awf"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awf"

  on_macos do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v0.0.3/awf_0.0.3_darwin_amd64.tar.gz"
      sha256 "f2c26af4860cc99d660156cece4f49d1b2b3ed24c745b4dbeba17f608f9a12b6"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v0.0.3/awf_0.0.3_darwin_arm64.tar.gz"
      sha256 "49f39a141dabadf268c9e2c7881d83494966e846fe88001d7747cd317d887c98"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v0.0.3/awf_0.0.3_linux_amd64.tar.gz"
      sha256 "aba82fd1def11f3d12150ffc7f198ce1761ecb361818e96fc45c5840a7832a7e"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v0.0.3/awf_0.0.3_linux_arm64.tar.gz"
      sha256 "e95b7ec7f90dfbdf5fe865f6d83f64427aa6ffdb4f7ae4cb40db8658d90e2659"
    end
  end

  # No zap stanza required
end
