# This file was generated by GoReleaser. DO NOT EDIT.
cask "awf" do
  desc "Find AWS resources"
  homepage "https://github.com/pete911/awf"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awf"

  on_macos do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v0.0.4/awf_0.0.4_darwin_amd64.tar.gz"
      sha256 "59153a3cce4a5eac49a303f3aa0d17d33d7f3c35ca8f65718645cfe11ff94b72"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v0.0.4/awf_0.0.4_darwin_arm64.tar.gz"
      sha256 "32cb3bc387e5f559dc0d3cf1275d4b264ebb670262e152f98dd655941af66f3f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v0.0.4/awf_0.0.4_linux_amd64.tar.gz"
      sha256 "a5f640e737ee57d1abddea23788ab1d153654dfb9fabdb46051e9e4ec0f70328"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v0.0.4/awf_0.0.4_linux_arm64.tar.gz"
      sha256 "d1dcce05181ff6cf0eb9a92342e090c8ee891993d48f1cfeb2b7ed18af6ec536"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awf"]
    end
  end

  # No zap stanza required
end
