# This file was generated by GoReleaser. DO NOT EDIT.
cask "awf" do
  name "awf"
  desc "Find AWS resources"
  homepage "https://github.com/pete911/awf"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awf"

  on_macos do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v#{version}/awf_#{version}_darwin_amd64.tar.gz"
      sha256 "3115928e1c8393bdb6f9e0e49d731721a857d314579fcb3ebdd1551f98650fa6"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v#{version}/awf_#{version}_darwin_arm64.tar.gz"
      sha256 "1d6fff12b236c5e46287ac7cc2a79eb2b869bceba8e89ef326c82c372aa5a28b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v#{version}/awf_#{version}_linux_amd64.tar.gz"
      sha256 "87296d88558a8891d7005180d8d1aa69317dedbab5200b281a5173c7d205b17c"
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v#{version}/awf_#{version}_linux_arm64.tar.gz"
      sha256 "8c9ce0ac558ee3ed08a0982e6b5c38a33155a9aab7e3a5fba69a49c024de7d53"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awf"]
    end
  end

  # No zap stanza required
end
