# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-vpn" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "d4e677fd8d6ee5161461d174248738ee834645c9ff35a3de924c39c97e82a2d0"
      url "https://github.com/pete911/aws-vpn/releases/download/v#{version}/aws-vpn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78093c829317371d54954847e4488ae0f5149bfa0067ac3b3f086b7554be5281"
      url "https://github.com/pete911/aws-vpn/releases/download/v#{version}/aws-vpn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0228d3764c62c21bdaf751d6d381f352638419830b0ee06bc4eb1a235553b7c6"
      url "https://github.com/pete911/aws-vpn/releases/download/v#{version}/aws-vpn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "56bdc12327f13e423d60d9a3046fb4d1a348c657834b5f83b5244678d1054ad1"
      url "https://github.com/pete911/aws-vpn/releases/download/v#{version}/aws-vpn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "aws-vpn"
  desc "Create VPN on AWS."
  homepage "https://github.com/pete911/aws-vpn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-vpn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-vpn"]
    end
  end

  # No zap stanza required

end
