# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip" do
  name "aws-ip"
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v#{version}/aws-ip_#{version}_darwin_amd64.tar.gz"
      sha256 "2f49854634d3e68b7db9776357cafea312cca0fdba41f8b0ed3877abfbbab1b7"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v#{version}/aws-ip_#{version}_darwin_arm64.tar.gz"
      sha256 "fab14bebd155a9a23feebbecb3dffbab323e29290c80100d4e99fbeb076e7b5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v#{version}/aws-ip_#{version}_linux_amd64.tar.gz"
      sha256 "9384bbe937541b82c0021f74109db84ece3aed987a7fa8a8fe57b4917ca90c7c"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v#{version}/aws-ip_#{version}_linux_arm64.tar.gz"
      sha256 "a156a131b3b191cc205fa8a699554e09ca5c61c8cbe7b0dcd2c9c602fff2a0d6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-ip"]
    end
  end

  # No zap stanza required
end
