# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-vpn" do
  desc "Create VPN on AWS."
  homepage "https://github.com/pete911/aws-vpn"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_darwin_amd64.tar.gz"
      sha256 "aa7a7b6885d85bce01334214a36da288a98e4200e624434052fcabac2d5e5730"
    end
    on_arm do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_darwin_arm64.tar.gz"
      sha256 "68f7a3c1db16e49964b7f5d21fd34768235eb0473b15aee3cfc1ad2226ae1ce3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_linux_amd64.tar.gz"
      sha256 "85c91d26cdcd39f8ec9db958f66b81118f485295db79fbc4f256bab20e288ed8"
    end
    on_arm do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_linux_arm64.tar.gz"
      sha256 "37a8af70f0ff50bee00e3214107c0a1426a05868898a2d39b3d617584cf660e8"
    end
  end

  # No zap stanza required
end
