# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-vpn" do
  desc "Create VPN on AWS."
  homepage "https://github.com/pete911/aws-vpn"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-vpn"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.5/aws-vpn_0.0.5_darwin_amd64.tar.gz"
      sha256 "e6f6c57d60fb66b87601fdde61a561852a225e915ef3a1e681628332531ba2a8"
    end
    on_arm do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.5/aws-vpn_0.0.5_darwin_arm64.tar.gz"
      sha256 "d2c23971d2d796bc4b33e02b5e644b1d39a59683b1d58029f7fa69cd9abc0538"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.5/aws-vpn_0.0.5_linux_amd64.tar.gz"
      sha256 "dc0d0e69f32504187d58dbe3ed1c7eecfc207fd9139eb10384bfcafc64fcfe90"
    end
    on_arm do
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.5/aws-vpn_0.0.5_linux_arm64.tar.gz"
      sha256 "299179069e4a12c580456664802f6b8f199f19128ef8a17bb4bd18e7ce5cc35d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-vpn"]
    end
  end

  # No zap stanza required
end
