# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip" do
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.5/aws-ip_1.0.5_darwin_amd64.tar.gz"
      sha256 "d587e2a6174842861bccd2b3c9605ddb03869efd59ea1b8c70d216823d8aa589"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.5/aws-ip_1.0.5_darwin_arm64.tar.gz"
      sha256 "22031c5c2514cf356ae17648f4a791304c59fe494629fd66577d883d3d52d02a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.5/aws-ip_1.0.5_linux_amd64.tar.gz"
      sha256 "1cb25596580abad703e9f133eb5749ce322044271ab80510549b1c5d09e799f1"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.5/aws-ip_1.0.5_linux_arm64.tar.gz"
      sha256 "8c0e710f3887b9bf50e1e11f0fd3b1325e8a03d0f5e746f8bd459885ccbe3169"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-ip"]
    end
  end

  # No zap stanza required
end
