# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-ip" do
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-ip"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.4/aws-ip_1.0.4_darwin_amd64.tar.gz"
      sha256 "162040b058a24a6ab350c0288ac44d6e35d9b04b81ffe91b833c1f739ec785e8"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.4/aws-ip_1.0.4_darwin_arm64.tar.gz"
      sha256 "87f31cf2360e900592ec07570a04533837f623dcf1ea528c03f95ec343b074ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.4/aws-ip_1.0.4_linux_amd64.tar.gz"
      sha256 "430ee503b5307cadc4ca6dfdfbc325ef9654d61e5d19a85f04c19ac0f9247943"
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.4/aws-ip_1.0.4_linux_arm64.tar.gz"
      sha256 "04cbac8a60234444e5f84baf1b88c25588b27a22fbf657341ee447cc61a90534"
    end
  end

  # No zap stanza required
end
