# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  name "certinfo"
  desc "Print x509 certificate info."
  homepage "https://github.com/pete911/certinfo"
  version "1.0.38"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "cc46eba3ef2aa5e01d8d1c7e0f9d3530bb18d6c9310cd751da60d98b8466d760"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "233405552528009524e1d170850f4744cd1abba9183b1f8ec45e7554e3fe83cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_amd64.tar.gz"
      sha256 "cf33aa8e920e3f65c4bee26c9bcd51fadc750beaa943af81f37e645c9dd10eb0"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_arm64.tar.gz"
      sha256 "aa7cd2fdd234bcf9d85e002cb067a0996a50395da520359fe4caa34693051223"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
    end
  end

  # No zap stanza required
end
