# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  desc "Print x509 certificate info."
  homepage "https://github.com/pete911/certinfo"
  version "1.0.34"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v1.0.34/certinfo_1.0.34_darwin_amd64.tar.gz"
      sha256 "671d9ea5a7ff98fd466ffa50e178c326423ddf47850da3ea7e3668f2624b799a"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v1.0.34/certinfo_1.0.34_darwin_arm64.tar.gz"
      sha256 "6a9f2e9f28d6a82de2c7bef5a850175f0f873f73449a8f093b8103cc6d3ab7e6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v1.0.34/certinfo_1.0.34_linux_amd64.tar.gz"
      sha256 "cd492afb74518d273ffa6c5c80fcba4f7c921d5177363347b06309144499cef3"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v1.0.34/certinfo_1.0.34_linux_arm64.tar.gz"
      sha256 "c215ed0a13c77840e5dfe30b63c018acf6104aa619775d096eb7937fc1307b9f"
    end
  end

  # No zap stanza required
end
