# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  name "certinfo"
  desc "Print x509 certificate info."
  homepage "https://github.com/pete911/certinfo"
  version "1.0.40"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_amd64.tar.gz"
      sha256 "7ba70ef013ccd49edb7ad34a448541198427008f8653a363940b677f7ed632dc"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_darwin_arm64.tar.gz"
      sha256 "eb63c103b6413b87aa6e144bd0aabfdefd167167e3684443726865bfff79cf65"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_amd64.tar.gz"
      sha256 "7e29240b66465144c6cf8a0ac5a6bb4bfdaa842f0e5d85fad2b3a5cfb00cd753"
    end
    on_arm do
      url "https://github.com/pete911/certinfo/releases/download/v#{version}/certinfo_#{version}_linux_arm64.tar.gz"
      sha256 "5d8c6d4937bad25ea287e0e0f04160e79753b196d15d6d4f2c3f1912d49cb592"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
    end
  end

  # No zap stanza required
end
