# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2" do
  name "ec2"
  desc "Create AWS EC2."
  homepage "https://github.com/pete911/ec2"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2"

  on_macos do
    on_intel do
      url "https://github.com/pete911/ec2/releases/download/v#{version}/ec2_#{version}_darwin_amd64.tar.gz"
      sha256 "1e7b6de2aa4e1e52d460746d56d33119251feaf3accad4267df87959367c6d86"
    end
    on_arm do
      url "https://github.com/pete911/ec2/releases/download/v#{version}/ec2_#{version}_darwin_arm64.tar.gz"
      sha256 "267dcc05690b2d8cac9b3cfd6ef1f1ecc01c63af369b444c50ebe69d977175e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/ec2/releases/download/v#{version}/ec2_#{version}_linux_amd64.tar.gz"
      sha256 "fe40f15dfecff21acf1b6c5c18ac08e69d93bec2b07ef7de9248d66701690bfe"
    end
    on_arm do
      url "https://github.com/pete911/ec2/releases/download/v#{version}/ec2_#{version}_linux_arm64.tar.gz"
      sha256 "7d8c28bf0ed43a2a8fd4b6b07d3fd1ef6bd43d410725c4a3298325c7bf78bf78"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ec2"]
    end
  end

  # No zap stanza required
end
