# This file was generated by GoReleaser. DO NOT EDIT.
cask "ec2" do
  desc "Create AWS EC2."
  homepage "https://github.com/pete911/ec2"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ec2"

  on_macos do
    on_intel do
      url "https://github.com/pete911/ec2/releases/download/v0.0.1/ec2_0.0.1_darwin_amd64.tar.gz"
      sha256 "8da786014a7e2ce64b33ea16c7cc07040d52648b1fd8882feb615d775f58861e"
    end
    on_arm do
      url "https://github.com/pete911/ec2/releases/download/v0.0.1/ec2_0.0.1_darwin_arm64.tar.gz"
      sha256 "d3ac45344e60482fc03b30b13e110a07cf656b09287dfec9cf6a0e1c9394c359"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/ec2/releases/download/v0.0.1/ec2_0.0.1_linux_amd64.tar.gz"
      sha256 "cc518d472e802d15481be49c8d90a3b1a9cab9141303f38ade0f153927eb60cf"
    end
    on_arm do
      url "https://github.com/pete911/ec2/releases/download/v0.0.1/ec2_0.0.1_linux_arm64.tar.gz"
      sha256 "789608e4ca35fd8abc927b6d2c1a1fe4bd9f2447ed4f163c1cfa8c03b8c8cf49"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ec2"]
    end
  end

  # No zap stanza required
end
