# This file was generated by GoReleaser. DO NOT EDIT.
cask "flowlogs" do
  name "flowlogs"
  desc "Create and view AWS FlowLogs."
  homepage "https://github.com/pete911/flowlogs"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flowlogs"

  on_macos do
    on_intel do
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_darwin_amd64.tar.gz"
      sha256 "132c2fde260a590db6aeac7617afc737c7b19e6858035966555b54589910aa17"
    end
    on_arm do
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_darwin_arm64.tar.gz"
      sha256 "56e28d6c85f41786515360a6634f2522f3301a00db434c7eabe7958ff3315b99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_linux_amd64.tar.gz"
      sha256 "7515fe35a3f4ce00d043ce6ec69b30b801cac55903c2f5cd547e41d482c6c132"
    end
    on_arm do
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_linux_arm64.tar.gz"
      sha256 "ec8d3d0d835771c15a54d2fbfd440f6ba2607ff6c55924ba39422576e221ac77"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flowlogs"]
    end
  end

  # No zap stanza required
end
