# This file was generated by GoReleaser. DO NOT EDIT.
cask "flowlogs" do
  version "0.0.13"

  on_macos do
    on_intel do
      sha256 "9df5f99b4af6f6eb892d4cd5d0712dab5657aa1f7246e2dc2728bb916c689e05"
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6247dedaeec8eae68efb59115234c6516684667289e70aa2960c7a63e8d4b306"
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5242dc23f7319dc9cd6a5294d7bb46e2e300188c53442a3774fbd090cab28431"
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c365d092e8c0d74c69b05a7e1af8f8276b921d11ceb321090c210ba531dc5761"
      url "https://github.com/pete911/flowlogs/releases/download/v#{version}/flowlogs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flowlogs"
  desc "Create and view AWS FlowLogs."
  homepage "https://github.com/pete911/flowlogs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flowlogs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flowlogs"]
    end
  end

  # No zap stanza required

end
