# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipcalc" do
  name "ipcalc"
  desc "IP calculator"
  homepage "https://github.com/pete911/ipcalc"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipcalc"

  on_macos do
    on_intel do
      url "https://github.com/pete911/ipcalc/releases/download/v#{version}/ipcalc_#{version}_darwin_amd64.tar.gz"
      sha256 "1792fa1a1ac04b97ee47f4365ec62604d5bae020bd9c7f89863800a64b557b85"
    end
    on_arm do
      url "https://github.com/pete911/ipcalc/releases/download/v#{version}/ipcalc_#{version}_darwin_arm64.tar.gz"
      sha256 "9ecb3b06c1015ef1e8d8a80fbbba1b77ca8a99bcbfe7c6d7627b79ffaff7c843"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/ipcalc/releases/download/v#{version}/ipcalc_#{version}_linux_amd64.tar.gz"
      sha256 "94b6e1f99c6169df1870c6c0876562ce41a20e59821f6aa4187fa208914ba35a"
    end
    on_arm do
      url "https://github.com/pete911/ipcalc/releases/download/v#{version}/ipcalc_#{version}_linux_arm64.tar.gz"
      sha256 "da03b642a2bde73f5af714412aca69ab1786cbd0a54e37d56947343afa69ee47"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ipcalc"]
    end
  end

  # No zap stanza required
end
