# This file was generated by GoReleaser. DO NOT EDIT.
cask "ipcalc" do
  desc "IP calculator"
  homepage "https://github.com/pete911/ipcalc"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ipcalc"

  on_macos do
    on_intel do
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.2/ipcalc_1.0.2_darwin_amd64.tar.gz"
      sha256 "bb5c0d2137cb5bb422383f29c98112713377dc6c5a6558379d616100ee03ef66"
    end
    on_arm do
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.2/ipcalc_1.0.2_darwin_arm64.tar.gz"
      sha256 "2c3ed0934acbe7aec52f56e280e8e7e2af1586cfb109a057b53662b9bd8ef94a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.2/ipcalc_1.0.2_linux_amd64.tar.gz"
      sha256 "bc73661ef18edb45772e51767edbb0a8575868a201ef71af001b32df6d00fac2"
    end
    on_arm do
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.2/ipcalc_1.0.2_linux_arm64.tar.gz"
      sha256 "c9c87f14d22c9c8a989760155f5f637669dcfd00ee7e2ebb8692c72a407069cf"
    end
  end

  # No zap stanza required
end
