# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awf < Formula
  desc "Find AWS resources"
  homepage "https://github.com/pete911/awf"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/pete911/awf/releases/download/v0.0.1/awf_0.0.1_darwin_amd64.tar.gz"
      sha256 "fbe458c24d3e6603d0553e3b6eab40673f4783c230552d9670b189a51747417b"

      def install
        bin.install "awf"
      end
    end
    on_arm do
      url "https://github.com/pete911/awf/releases/download/v0.0.1/awf_0.0.1_darwin_arm64.tar.gz"
      sha256 "8d04020043fe64ea62759e8b3a98d6fe62aa407ca6f26dc81768e0f6738d694a"

      def install
        bin.install "awf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/awf/releases/download/v0.0.1/awf_0.0.1_linux_amd64.tar.gz"
        sha256 "677428162b2258ebb4c0faec0d9f59d1ba3c1bf92cd3dbf74f563dc335c1a0b7"

        def install
          bin.install "awf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/awf/releases/download/v0.0.1/awf_0.0.1_linux_arm64.tar.gz"
        sha256 "58ec80b8bbd554a2d2498478acbeb6226faf6d31c85df23efd0d09f8686aeeaa"

        def install
          bin.install "awf"
        end
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/awf -h", 0)
  end
end
