# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awf < Formula
  version "0.0.3"
  disable! date: "2025-07-04", because: "the cask should be used now instead", replacement_cask: "awf"
end
