# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVpn < Formula
  desc "Create VPN on AWS."
  homepage "https://github.com/pete911/aws-vpn"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_darwin_amd64.tar.gz"
      sha256 "aa7a7b6885d85bce01334214a36da288a98e4200e624434052fcabac2d5e5730"

      def install
        bin.install "aws-vpn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_darwin_arm64.tar.gz"
      sha256 "68f7a3c1db16e49964b7f5d21fd34768235eb0473b15aee3cfc1ad2226ae1ce3"

      def install
        bin.install "aws-vpn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_linux_amd64.tar.gz"
      sha256 "85c91d26cdcd39f8ec9db958f66b81118f485295db79fbc4f256bab20e288ed8"
      def install
        bin.install "aws-vpn"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/aws-vpn/releases/download/v0.0.1/aws-vpn_0.0.1_linux_arm64.tar.gz"
      sha256 "37a8af70f0ff50bee00e3214107c0a1426a05868898a2d39b3d617584cf660e8"
      def install
        bin.install "aws-vpn"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/aws-vpn -h", 0)
  end
end
