# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsIp < Formula
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.0/aws-ip_1.0.0_darwin_amd64.tar.gz"
      sha256 "32d204ca298b201fdc79e583c317030e7364c6a42ba10fbf363ef30aaade5f0b"

      def install
        bin.install "aws-ip"
      end
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.0/aws-ip_1.0.0_darwin_arm64.tar.gz"
      sha256 "9674477ec68f2f0826c12cf1a81c35fff3ba4b67ea357608c02c3f092a070a78"

      def install
        bin.install "aws-ip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.0/aws-ip_1.0.0_linux_amd64.tar.gz"
        sha256 "c078822f02a08f29e3e19e87970b80f1362492712b49068778f34326a1beae01"

        def install
          bin.install "aws-ip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.0/aws-ip_1.0.0_linux_arm64.tar.gz"
        sha256 "1ef10a3ec569c04b608c57e7169b86076955070623fcd783cd833faadb1c71d2"

        def install
          bin.install "aws-ip"
        end
      end
    end
  end

  test do
    assert_match /version/, shell_output("#{bin}/aws-ip", 0)
  end
end
