# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsIp < Formula
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.2/aws-ip_1.0.2_darwin_amd64.tar.gz"
      sha256 "7a664e1a871c07dd0cd7ac3608e929732d69bf9594349a9cc3aabd15d2089150"

      def install
        bin.install "aws-ip"
      end
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.2/aws-ip_1.0.2_darwin_arm64.tar.gz"
      sha256 "b4f6f0f3bbd418c2aa9ca956001e3159ef3f1cefec693a4eb3eeffd9f98915f3"

      def install
        bin.install "aws-ip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.2/aws-ip_1.0.2_linux_amd64.tar.gz"
        sha256 "1a3ab08e58c72da17db2a96d06ad9b73c6fa78bc73f746f967f20062cc5a6841"

        def install
          bin.install "aws-ip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.2/aws-ip_1.0.2_linux_arm64.tar.gz"
        sha256 "313bf6772fdadb2b30e83d423c410ef797d27248b98594d4591d3ae6ddda7120"

        def install
          bin.install "aws-ip"
        end
      end
    end
  end

  test do
    assert_match /version/, shell_output("#{bin}/aws-ip", 0)
  end
end
