# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsIp < Formula
  desc "find ip for aws services"
  homepage "https://github.com/pete911/aws-ip"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.1/aws-ip_1.0.1_darwin_amd64.tar.gz"
      sha256 "aec751ce063eb0a11f31aea89b6b09730c5502dc29e51253e1d5251422375c70"

      def install
        bin.install "aws-ip"
      end
    end
    on_arm do
      url "https://github.com/pete911/aws-ip/releases/download/v1.0.1/aws-ip_1.0.1_darwin_arm64.tar.gz"
      sha256 "fa4acbb7046626b6abe1423d826463c30471bacea6a15e53dbae3f83f7ae2b50"

      def install
        bin.install "aws-ip"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.1/aws-ip_1.0.1_linux_amd64.tar.gz"
        sha256 "b3404b4a688973c70f63529020dd53e76419bac78e4a3133dd45d8d6308f9cd6"

        def install
          bin.install "aws-ip"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/aws-ip/releases/download/v1.0.1/aws-ip_1.0.1_linux_arm64.tar.gz"
        sha256 "4f915c703bea144100bd8a25b46f53df66f1248add5a429428ae9c53b4daa675"

        def install
          bin.install "aws-ip"
        end
      end
    end
  end

  test do
    assert_match /version/, shell_output("#{bin}/aws-ip", 0)
  end
end
