# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certinfo < Formula
  desc "Print x509 certificate info."
  homepage "https://github.com/pete911/certinfo"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/certinfo/releases/download/v1.0.8/certinfo_1.0.8_darwin_amd64.tar.gz"
      sha256 "841699a5399371b7ef5c455e44e76cde9c3ebaa4fb3f217d6b8e4f4b12901e31"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/certinfo/releases/download/v1.0.8/certinfo_1.0.8_darwin_arm64.tar.gz"
      sha256 "1b65b1b3362a7e8755aa97540d8a7862ea7b7423f865e45649f476e085ac8340"

      def install
        bin.install "certinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/certinfo/releases/download/v1.0.8/certinfo_1.0.8_linux_arm64.tar.gz"
      sha256 "f66fa3dfdae5edf8add49857864f26f817a6edaae4168ecfd417945286af7d05"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/certinfo/releases/download/v1.0.8/certinfo_1.0.8_linux_amd64.tar.gz"
      sha256 "4dc31fd1b73bef0bdbf913675a985146d4e8c20a27ca9091ff30db9762d45049"

      def install
        bin.install "certinfo"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/certinfo -h", 0)
  end
end
