# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowlogs < Formula
  desc "Create and view AWS FlowLogs."
  homepage "https://github.com/pete911/flowlogs"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/flowlogs/releases/download/v0.0.8/flowlogs_0.0.8_darwin_amd64.tar.gz"
      sha256 "582e596a6bcb6abadd5ee3099fdd014d460bac32553626a9dccb3bfaacf193cd"

      def install
        bin.install "flowlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/flowlogs/releases/download/v0.0.8/flowlogs_0.0.8_darwin_arm64.tar.gz"
      sha256 "768ee96560182b7215ec76d63414b7cec72ad022d06a873682d78b87f80daa87"

      def install
        bin.install "flowlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/flowlogs/releases/download/v0.0.8/flowlogs_0.0.8_linux_amd64.tar.gz"
        sha256 "feae1ca02734bac63f979010eac06603b4afaaf74c7f546cca784438075c6541"

        def install
          bin.install "flowlogs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/flowlogs/releases/download/v0.0.8/flowlogs_0.0.8_linux_arm64.tar.gz"
        sha256 "9fde87def64db40782a09dfdd0a13651fbc4356b9460476eea2e5324cab4292e"

        def install
          bin.install "flowlogs"
        end
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/flowlogs -h", 0)
  end
end
