# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowlogs < Formula
  desc "Create and view AWS FlowLogs."
  homepage "https://github.com/pete911/flowlogs"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/flowlogs/releases/download/v0.0.4/flowlogs_0.0.4_darwin_amd64.tar.gz"
      sha256 "42901c288e3e57eb374eaa1fa1bc8e22e4e25196c66a98b9cc7be8fd0432ce7d"

      def install
        bin.install "flowlogs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/flowlogs/releases/download/v0.0.4/flowlogs_0.0.4_darwin_arm64.tar.gz"
      sha256 "4fa060d56c738ddacf14edacdf47958caf975fcbd3fb35d1148f490ef3050b0a"

      def install
        bin.install "flowlogs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/flowlogs/releases/download/v0.0.4/flowlogs_0.0.4_linux_amd64.tar.gz"
        sha256 "e0d15813c228bab2aa6b44f0e16143cea1a501a7e7ae05a50b65a880538a3191"

        def install
          bin.install "flowlogs"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pete911/flowlogs/releases/download/v0.0.4/flowlogs_0.0.4_linux_arm64.tar.gz"
        sha256 "b4c55a8ad876fb5083e4a7d91b23e5cfb0ccb240b55cc602f3f828ba8655f229"

        def install
          bin.install "flowlogs"
        end
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/flowlogs -h", 0)
  end
end
