# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoUpdate < Formula
  desc "Update go git projects."
  homepage "https://github.com/pete911/go-update"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/go-update/releases/download/v1.0.0/go-update_1.0.0_darwin_amd64.tar.gz"
      sha256 "c9fb46b55f4296acf84245cc6f8508862d691792e921d8009bea311d172cbbee"

      def install
        bin.install "go-update"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/go-update/releases/download/v1.0.0/go-update_1.0.0_darwin_arm64.tar.gz"
      sha256 "569980cd6cb22b7120d791e53fc74ef7356a134440f44fdc6ff57f378879e54b"

      def install
        bin.install "go-update"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/go-update/releases/download/v1.0.0/go-update_1.0.0_linux_amd64.tar.gz"
      sha256 "af7ad1c1f9a5ee899065a8a560c04f6432c5db86042fc89b4cad966d9b9f211c"

      def install
        bin.install "go-update"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/go-update/releases/download/v1.0.0/go-update_1.0.0_linux_arm64.tar.gz"
      sha256 "7972bd95369ed070170a37cd57841ff3b48c8553e4507591723218da1e610344"

      def install
        bin.install "go-update"
      end
    end
  end
end
