# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcr < Formula
  desc "GitHub pages helm chart releaser."
  homepage "https://github.com/pete911/hcr"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pete911/hcr/releases/download/v0.0.3/hcr_0.0.3_darwin_arm64.tar.gz"
      sha256 "fced49b126560627547f76804e252dbbc124051265581adf079667c02d95a3d8"

      def install
        bin.install "hcr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/hcr/releases/download/v0.0.3/hcr_0.0.3_darwin_amd64.tar.gz"
      sha256 "5030851eec1d329854b758662151e347295aa5f5cb30277f8b2aea3f0a2f07b2"

      def install
        bin.install "hcr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/hcr/releases/download/v0.0.3/hcr_0.0.3_linux_arm64.tar.gz"
      sha256 "be374e5749736494f28b709d98f86fe8224b0f37887cf3753c8313b87b0ed7d7"

      def install
        bin.install "hcr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/hcr/releases/download/v0.0.3/hcr_0.0.3_linux_amd64.tar.gz"
      sha256 "1a312359f86e390c1ca34505038fd3f76706ee653325a9004bbb46c059e30ff8"

      def install
        bin.install "hcr"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/hcr -h", 0)
  end
end
