# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipcalc < Formula
  desc "IP calculator"
  homepage "https://github.com/pete911/ipcalc"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.0/ipcalc_1.0.0_darwin_amd64.tar.gz"
      sha256 "471f5ae5ee84e77d3db12cbbb825eaa4604de0f38a69e092d016f7a4fffec338"
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.0/ipcalc_1.0.0_darwin_arm64.tar.gz"
      sha256 "f27445a2bb0b37be93b0413cc85ba86051271a2526d9dc953b2cceb8270f05d4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.0/ipcalc_1.0.0_linux_amd64.tar.gz"
      sha256 "2c007b1de0c5eea03c9433465e39bb05d09dce25d5ba4127e82e11d220348103"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/ipcalc/releases/download/v1.0.0/ipcalc_1.0.0_linux_arm64.tar.gz"
      sha256 "40655592cd5129330a2ff060927291fbd761c754020193646194127f42474307"
    end
  end

  def install
    bin.install "ipcalc"
  end

  test do
    assert_match /version/, shell_output("#{bin}/ipcalc", 0)
  end
end
