# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jwt < Formula
  desc "jwt cli"
  homepage "https://github.com/pete911/jwt"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/jwt/releases/download/v1.0.3/jwt_1.0.3_darwin_amd64.tar.gz"
      sha256 "8320154e1e7fcc80ed948357dfd04aa8dd91fdc09ea93a52d50c5e51689124e8"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/jwt/releases/download/v1.0.3/jwt_1.0.3_darwin_arm64.tar.gz"
      sha256 "d3069d66a8c7aa1b914389bae2213bcf70c4e5dd98c500ce6b6683e69ae91116"

      def install
        bin.install "jwt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/jwt/releases/download/v1.0.3/jwt_1.0.3_linux_amd64.tar.gz"
      sha256 "8b9a1391da9e486f00313f3b7c6a508aeca7dcbd689e0ed87c0e22f7f5707a31"

      def install
        bin.install "jwt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/jwt/releases/download/v1.0.3/jwt_1.0.3_linux_arm64.tar.gz"
      sha256 "e2614999db36b55b29e323942c4045fbc92d862fdeb876fc9f71c0b033ca517a"

      def install
        bin.install "jwt"
      end
    end
  end

  test do
    assert_match /jwt/, shell_output("#{bin}/jwt -h", 0)
  end
end
