# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlIam4sa < Formula
  desc "debug IAM roles for service accounts"
  homepage "https://github.com/pete911/kubectl-iam4sa"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pete911/kubectl-iam4sa/releases/download/v1.0.3/kubectl-iam4sa_1.0.3_darwin_arm64.tar.gz"
      sha256 "e3c2a2e69a8287131822d103e521341dc9c96c4161e340ae989e0e61c15a2719"

      def install
        bin.install "kubectl-iam4sa"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-iam4sa/releases/download/v1.0.3/kubectl-iam4sa_1.0.3_darwin_amd64.tar.gz"
      sha256 "a52ba11f777749df1b798aa95f0d8c4748ead81503e26deafded16c27bc52e20"

      def install
        bin.install "kubectl-iam4sa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-iam4sa/releases/download/v1.0.3/kubectl-iam4sa_1.0.3_linux_amd64.tar.gz"
      sha256 "78917588768658bcbf60a4523391b0f39e0f2ff66fcb8d01381ea75d3a90b6e7"

      def install
        bin.install "kubectl-iam4sa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/kubectl-iam4sa/releases/download/v1.0.3/kubectl-iam4sa_1.0.3_linux_arm64.tar.gz"
      sha256 "0bcddeecbdb21238fbf2c8c249a686a10668306fce5e9334a85f65ccc0a59cef"

      def install
        bin.install "kubectl-iam4sa"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/kubectl-iam4sa -h", 0)
  end
end
