# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlImage < Formula
  desc "List images in kubernetes cluster."
  homepage "https://github.com/pete911/kubectl-image"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.2/kubectl-image_1.0.2_darwin_arm64.tar.gz"
      sha256 "17676712949bd55e660c8482b9f724a21201b46abfe6565fd5538cdcb0d30c43"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.2/kubectl-image_1.0.2_darwin_amd64.tar.gz"
      sha256 "53d766f0127076676f328baa6a2a550e5fe0a0654bc4aee62585fc5e2e8db5e5"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.2/kubectl-image_1.0.2_linux_arm64.tar.gz"
      sha256 "f51276483d36a69f9ccacf0be49c387f8af532400459ba83ef8da892c883bd66"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.2/kubectl-image_1.0.2_linux_amd64.tar.gz"
      sha256 "43f3fc2c291a3b2009dc2666b74f067329fb29f5c79b3d513bccf80ea032bd14"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/kubectl-image -h", 0)
  end
end
