# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlImage < Formula
  desc "List images in kubernetes cluster."
  homepage "https://github.com/pete911/kubectl-image"
  version "1.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.6/kubectl-image_1.0.6_darwin_amd64.tar.gz"
      sha256 "4026a6cab695831672ee2dd18008385608973b4d3cf8c73200aba1bef6752707"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.6/kubectl-image_1.0.6_darwin_arm64.tar.gz"
      sha256 "6dcc806f8625b33a84c404d22ef74b831068727d6448eb6588fe61342339e511"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.6/kubectl-image_1.0.6_linux_arm64.tar.gz"
      sha256 "41324c550391086686766edc760035bcdd2e80e6b8654e332c6ef741bc4b9987"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.6/kubectl-image_1.0.6_linux_amd64.tar.gz"
      sha256 "c263058e8f88c3b78b5a465be12bd50dad2a69ea37ee1ab04a81bda060ea17a5"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/kubectl-image -h", 0)
  end
end
