# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlImage < Formula
  desc "List images in kubernetes cluster."
  homepage "https://github.com/pete911/kubectl-image"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.3/kubectl-image_1.0.3_darwin_arm64.tar.gz"
      sha256 "3e79b4439590803992d5aeb2adb8c3e22e0fc957f0843b3cdbb8cbc0aaa50721"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.3/kubectl-image_1.0.3_darwin_amd64.tar.gz"
      sha256 "4dda8aac227b146bef3564a53c4103b8191de39959722a9a7e823e9f4681173d"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.3/kubectl-image_1.0.3_linux_amd64.tar.gz"
      sha256 "c1dcfb51de351532456549087d73bbb2c83a231c9aa34b576df65ab704ed80a0"

      def install
        bin.install "kubectl-image"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/kubectl-image/releases/download/v1.0.3/kubectl-image_1.0.3_linux_arm64.tar.gz"
      sha256 "3ca539ea719d4b890ea6d846c2a579d1926599e5786842640b995116c8ed757f"

      def install
        bin.install "kubectl-image"
      end
    end
  end

  test do
    assert_match /Usage/, shell_output("#{bin}/kubectl-image -h", 0)
  end
end
