# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lookup < Formula
  desc "Lookup domain information."
  homepage "https://github.com/pete911/lookup"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pete911/lookup/releases/download/v1.0.1/lookup_1.0.1_darwin_amd64.tar.gz"
      sha256 "eb929f940816a773c25bdf0f3ce388c08bab96b94941577a4b0cd7fac40cabf4"

      def install
        bin.install "lookup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pete911/lookup/releases/download/v1.0.1/lookup_1.0.1_darwin_arm64.tar.gz"
      sha256 "5097df0e7b782d58a2759c765b9f79618fce4cb3efcffb60e5e33068d79cd978"

      def install
        bin.install "lookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/lookup/releases/download/v1.0.1/lookup_1.0.1_linux_arm64.tar.gz"
      sha256 "aed6ff774381743fd2589f77d458d7c9f14010ac7872c0dfd235713b47e83a1b"

      def install
        bin.install "lookup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/lookup/releases/download/v1.0.1/lookup_1.0.1_linux_amd64.tar.gz"
      sha256 "e4f95bb1fbf281f55fac7072dbedcf202020b368882409583d76773864ce0e73"

      def install
        bin.install "lookup"
      end
    end
  end
end
