# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lookup < Formula
  desc "Lookup domain information."
  homepage "https://github.com/pete911/lookup"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pete911/lookup/releases/download/v1.0.0/lookup_1.0.0_darwin_arm64.tar.gz"
      sha256 "c6683d5e8aa26894175d0c121f2dd46ae4c01964a18785a01a5be60cb187844f"

      def install
        bin.install "lookup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/lookup/releases/download/v1.0.0/lookup_1.0.0_darwin_amd64.tar.gz"
      sha256 "1b7eb29cecbe263be5585026c04cd5e9805ba6185040a1594bba60de71a61dc0"

      def install
        bin.install "lookup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pete911/lookup/releases/download/v1.0.0/lookup_1.0.0_linux_arm64.tar.gz"
      sha256 "051375238a99b468f9809c1a3f36d913d6f273819459b7ca01e23074a944a9c4"

      def install
        bin.install "lookup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pete911/lookup/releases/download/v1.0.0/lookup_1.0.0_linux_amd64.tar.gz"
      sha256 "954b55084675e764c84d40da85c8babe0ca5840b82343fd317d6efd106bb7e1b"

      def install
        bin.install "lookup"
      end
    end
  end
end
